cp -r ./layers/utils.js ./auth 
cp -r ./layers/AWSLayer.js  ./auth 
cp -r ./layers/utils.js ./loans/newLoanFlow
cp -r ./layers/utils.js ./loans/paymentMethods
cp -r ./layers/utils.js ./loans/purchaseManagement
cp -r ./layers/utils.js ./loans/scheduledEvents
cp -r ./layers/models.js ./loans/scheduledEvents
cp -r ./layers/utils.js ./merchants
cp -r ./layers/utils.js ./merchants/direct
cp -r ./layers/models.js ./merchants/direct
cp -r ./layers/utils.js ./push
cp -r ./layers/utils.js ./recovery 
cp -r ./layers/utils.js ./users 
cp -r ./layers/AWSLayer.js ./users 
cp -r ./layers/utils.js ./users/email
cp -r ./layers/utils.js ./support 
cp -r ./layers/utils.js ./loans/wallet 
cp -r ./layers/AWSLayer.js ./loans/wallet
cp -r ./layers/LerexLayer.js ./loans/wallet